{% set name = "rapidgzip" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba1ed7ce1c7894a37c06e33a46c15b5a38b490780f44095945aeb3505efeacc1

build:
  entry_points:
    - rapidgzip=rapidgzip:cli
  script_env:
    - RAPIDGZIP_BUILD_CXXOPTS=system
    - RAPIDGZIP_BUILD_ISAL=disable
    - RAPIDGZIP_BUILD_RPMALLOC=disable
    - RAPIDGZIP_BUILD_ZLIB=system
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - nasm
  host:
    - libcxx {{ cxx_compiler_version }}  # [osx]
    - python
    - cython >=0.29.24
    - pip
    - cxxopts >=3,<4
    - zlib >=1.2.3,<2
  run:
    - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
    - python

test:
  imports:
    - rapidgzip
  commands:
    - pip check
    - rapidgzip --help
  requires:
    - pip

about:
  home: https://github.com/mxmlnkn/rapidgzip
  summary: Parallel random access to bzip2 and gzip files
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT

extra:
  recipe-maintainers:
    - ap--
    - mxmlnkn
